### ISSUE TITLE
Move from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by florisvdh** [inbo/tutorials#225]
Just adding an issue to keep track and allow further discussion.

The need for migrating to GitHub Actions was encountered in PR https://github.com/inbo/tutorials/pull/221#issuecomment-769633547 and comments thereafter. See also the less-urgent PR #223 which could be used to finally test that it works.

@niconoe I've added you as assignee based on latest discussions, feel free to update if needed.

**Comment by florisvdh** [comment]
Given that updates have been done to some tutorials recently, and a few more are in the pipeline, I'm available to rebuild the website locally from `master` when needed / as long as needed (using same `hugo` setup as Travis) and push the result to `gh-pages`. Just let know when there's a need to update.

**Comment by niconoe** [comment]
Thanks for the reminder, @florisvdh. Perfect timing, since I'm today working with GitHub actions to prepare an internal infosession about them, and just configured them for a similar auto-deployment for https://inbo.github.io/crow/#/.

So I'll investigate right now!

**Comment by niconoe** [comment]
Hey @florisvdh, I just implemented a first version with Google actions, here is where we stand:

- Website is automatically updated on each push to the `master` branch. As far as I know, it works as intended (don't hesitate to check)
- To make debugging easier, the website now shows the build date/time at the bottom of the sidebar (we can remove that if it's an issue)
- I'm not sure of what we should do regarding pull requests: I guess we don't want to change the official website before a PR gets accepted? But at the same time it would be great if we could preview those PR... I was thinking that a great solution would be to deploy a new copy of the tutorials website at another address (branch? subdirectory?) for each pull request. But I'm not sure if/how this is possible and wanted your opinion first.

thanks for the feedback!

**Comment by florisvdh** [comment]
Nice work @niconoe :tada: - thanks a lot!! The website rebuilds, and it all seems to work as expected :+1: .

Good idea to add the 'built on'. (BTW while tweaking the website you're welcome to tackle #151, #155, #215, they also deal with specific aspects of website layout/configuration)

Some suggestions and answers:

- `runs-on: ubuntu-18.04`: did you try `ubuntu-20.04`? It would give us 2 extra years before another OS migration is needed (2025).
- `run: hugo -D`: I think `-D` is not needed for us (see `hugo --help` or https://gohugo.io/getting-started/usage/). Anyway we don't apply `draft: true` in tutorials at the moment. And if we did, I presume we don't want them published (which does happen with `-D`)
- typo? `Build on: {{ now.Format "Mon Jan 2 15:04:05 MST 2006" }}` --> `Built on {{...`
- pull requests: you could also save the website as an artifact, it will be held available at GitHub for 90 days, as a zip-file which can then can be downloaded and viewed locally. It doesn't seem necessary to actually publish a dev site IMO, it could also cause confusion. Having stepped to GHA only recently (for the same reason), I did such thing for an R package website. Maybe you find [this example](https://github.com/inbo/n2khab/blob/a7c450a9198180e06e340c30443d94111e4584c8/.github/workflows/site-devel.yaml#L58-L62) useful.

**Comment by niconoe** [comment]
Thanks @florisvdh, excellent suggestions, I'll look into that very soon!

**Comment by niconoe** [comment]
@florisvdh : I have implemented all your suggestions (except the 3 other issues to tackle, but I hope to find time for them soon).

For pull request, you can see a live example here: https://github.com/inbo/tutorials/pull/234. I also added a comment with a link to the artifact in the PR itself. Hope you like it!

**Comment by niconoe** [comment]
Another good remark in the PR: 

`does the artifact-website render well on your PC? I believe its hyperlinks are hardcoded relative to root? With hugo one can pass -b to change base directory, but not clear to me how to make it work in a directory-independent (relative?) way.`

To be investigated soon!

**Comment by florisvdh** [comment]
Thanks @niconoe for this wonderful work :tada: . The message by the github-actions bot is a nice bonus!

**Comment by niconoe** [comment]
@florisvdh: I've investigated the relative URLs issues, and I concluded it's quite difficult to fix the build so it is immediately displayable without any server on a development machine. There are multiple reasons for that*.

I *do* have a workaround to successfully display the artifacts, but it's not as elegant as I'd like (and needs a Python 3 install):

1) Download the artifact
2) Decompress it and **make sure the target directory is called 'tutorials'** (you may need to rename it)
3) From the parent directory (just above `tutorials`), run `python -m http.server`
4) Point your browser to `http://localhost:8000/tutorials`

Do you think that's good enough for now? Should we document this workaround (in a more visible place than this issue?)?

*Reasons:

- many links in the tutorials site are absolute and start with `/tutorials`. The '-b' flag you mentioned has no effect on those.
- when a web browser is used to list a local directory content, it will always list all files (even if there's an `index.html` in it). Our links don't account for that.
- More generally, it seems the Hugo philosophy is that the integrated web server should be used in those cases.

**Comment by florisvdh** [comment]
@niconoe thanks for the explanation and for finding this solution.

Note that on Ubuntu 20.04 one needs to explicitly use `python3` on the command line (or `python2`, but that is not recommended). On Ubuntu 18.04 `python` still exists as such and refers `python2.7`. I tested (with `python3`) and it works :+1:.

> Do you think that's good enough for now?

Yes, I think so. But maybe less convenient for those who don't have python already.

Some alternatives are listed at https://stackoverflow.com/questions/12905426/what-is-a-faster-alternative-to-pythons-http-server-or-simplehttpserver, probably some more exist. One caught my eye, it is the chrome-app [Web Server for Chrome](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb/related?hl=en). For the tutorials, its usage is similar: start the app, point it to the directory above the tutorials folder and in the web browser go to http://localhost:8887/tutorials/ . So this could also be given as an alternative, as most colleagues use Chrome already.

> Should we document this workaround (in a more visible place than this issue?)?

Sure. Perhaps, for now, this can just be stored in a separate markdown file in the repository root (e.g. `reviewing.md`), and referred by the github-actions bot in its message? Or it could also be featured on the website itself, as a separate short tutorial, linked by the bot! Cf. the tutorial on how to write a tutorial.

Anyway, I feel that having the hardcoded link to `/tutorials` in the website seems not ideal. Not sure whether it can be avoided. E.g. the pkgdown [example](https://github.com/inbo/n2khab/blob/a7c450a9198180e06e340c30443d94111e4584c8/.github/workflows/site-devel.yaml#L58-L62) can be rendered anywhere, clicking `index.html` suffices.

**Comment by niconoe** [comment]
@florisvdh: I've implemented the last suggestions above + what has been discussed by email (security considerations, `REVIEWING.md`, workflow executed for PR on all branches, ...).

Can you have a look? thanks!

**Comment by niconoe** [comment]
@florisvdh: for Python 2, there's an easy fix: just use `python -m SimpleHTTPServer`

**Comment by florisvdh** [comment]
Thanks @niconoe I think everything is running fine! Final suggestions added in PR #238.

**Comment by florisvdh** [comment]
@niconoe unless you still had other plans relating to GHA, I think this can be closed.
